const fs = require("fs");
const path = require("path");

async function ConfigFilesProcessor(config) {
  if (!config) {
    throw new Error("NoConfigurationFileException");
  }

  for (const flavor of config.flavors) {
    const { flavorName, extra } = flavor;

    if (!extra || !extra.configFiles) {
      continue;
    }

    for (const configFile of extra.configFiles) {
      const { output } = configFile;

      // Generate environment.js content
      const content = generateEnvironmentContent(flavor);

      // Ensure output directory exists
      const outputDir = path.dirname(output);
      if (!fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir, { recursive: true });
      }

      // Write content to output file
      fs.writeFileSync(output, content);
    }
  }
}

function generateEnvironmentContent(flavor) {
  const { flavorName, appName, android, extra } = flavor;

  return `// Auto-generated by expo-flavorizer
const ENVIRONMENT = {
  BRAND: "${flavorName}",
  APP_NAME: "${appName}",
  BUNDLE_ID: "${android.applicationId}",
  CURRENCY: "${extra?.currency || 'MXN'}",
  CURRENCY_SIGN: "${extra?.currencySign || '$'}",
  API_KEY: "${extra?.apiKey || ''}",
  SEARCH_URL: "${extra?.searchUrl || ''}",
  PURCHASE_URL: "${extra?.purchaseUrl || ''}",
  ORIGIN_HEADER: "${extra?.originHeader || ''}"
};

export default ENVIRONMENT;
`;
}

module.exports = ConfigFilesProcessor;
